### ISSUE TITLE
Number of Subpopulation

### ISSUE THREAD

**Issue by tuanvu92** [zweifel/Physis-Shard#1]
@zweifel  In the paper SUNA, the number of subpopulation can be larger than 1. Why in the demo code you only use 1 (`ERROR: Number of subpopulations is different than 1`)

**Comment by zweifel** [comment]
Sorry for the misleading name. What I think you are looking for is the SUBPOPULATION_SIZE variable which defines the size of a Novelty Map and was mentioned in the paper. NUMBER_OF_SUBPOPULATIONS was an extension that I was considering but never had the time to finish it. Below are the definitions:

1- NUMBER_OF_SUBPOPULATIONS - The number of Novelty Map Populations (always considered 1 in the article). 
2- SUBPOPULATION_SIZE - Number of cells in a Novelty Map Population
